[toolchain]
anchor_version = "0.32.1"

[workspace]
members = ["programs/nakama_coverage_protocol", "programs/nakama_private_claim_review"]

[programs.localnet]
nakama_coverage_protocol = "6EXiDfGVbG7V1X2xaEALDZ7CtSuezkM8ZvXXFpk5WxQM"
nakama_private_claim_review = "FADqaRcJHERauzMo3BRzXZVY2qvrpPqg1ie2FGqACCVn"

[programs.devnet]
nakama_coverage_protocol = "6EXiDfGVbG7V1X2xaEALDZ7CtSuezkM8ZvXXFpk5WxQM"
nakama_private_claim_review = "FADqaRcJHERauzMo3BRzXZVY2qvrpPqg1ie2FGqACCVn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "node --import tsx --test tests/**/*.test.ts"
