// ---- GENERATED BY QEDGEN — DO NOT EDIT ---- spec-hash:91f848c181f7a377
pub mod create_reserve_domain;
pub mod update_reserve_domain_controls;
pub mod create_domain_asset_vault;
pub mod create_health_plan;
pub mod update_health_plan_controls;
pub mod create_policy_series;
pub mod version_policy_series;
pub mod open_funding_line;
pub mod fund_sponsor_budget;
pub mod record_premium_payment;
pub mod deposit_reserve_capital;
pub mod return_reserve_capital;
pub mod record_reserve_earnings;
pub mod create_obligation;
pub mod reserve_obligation;
pub mod settle_obligation;
pub mod release_reserve;
pub mod open_claim_case;
pub mod authorize_claim_recipient;
pub mod adjudicate_claim_case;
pub mod settle_claim_case;
// ---- END GENERATED ----
