// ---- GENERATED BY QEDGEN — DO NOT EDIT — regenerated from .qedspec ----
//! Per-handler guard checks derived from the `.qedspec`.
//! Called from user-owned `instructions/<name>::handler` before
//! business logic; keep guard logic here, policy-free logic there.

#![allow(unused_variables, unused_imports, dead_code, clippy::too_many_arguments)]

use anchor_lang::prelude::*;
use crate::errors::*;
use crate::state::*;
use crate::*;

fn read_model_account(account_info: &AccountInfo) -> Result<OmegaxProtocolAccount> {
    let data = account_info.try_borrow_data()?;
    OmegaxProtocolAccount::try_deserialize(&mut data.as_ref())
}

fn account_emergency_pause(account_info: &AccountInfo) -> Result<bool> {
    Ok(read_model_account(account_info)?.emergency_pause)
}

fn account_active(account_info: &AccountInfo) -> Result<bool> {
    Ok(read_model_account(account_info)?.active)
}

fn account_paid_amount(account_info: &AccountInfo) -> Result<u64> {
    Ok(read_model_account(account_info)?.paid_amount)
}

fn account_approved_amount(account_info: &AccountInfo) -> Result<u64> {
    Ok(read_model_account(account_info)?.approved_amount)
}

fn account_withdrawn_fees(account_info: &AccountInfo) -> Result<u64> {
    Ok(read_model_account(account_info)?.withdrawn_fees)
}

fn account_accrued_fees(account_info: &AccountInfo) -> Result<u64> {
    Ok(read_model_account(account_info)?.accrued_fees)
}

fn account_max_confidence_bps(account_info: &AccountInfo) -> Result<u64> {
    Ok(read_model_account(account_info)?.max_confidence_bps)
}


/// Guards for `create_reserve_domain`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn create_reserve_domain<'info>(ctx: &mut CreateReserveDomain<'info>, args: CreateReserveDomainArgs) -> Result<()> {
    // lifecycle: require status == Live
    if ctx.reserve_domain.status != Status::Live as u8 { return Err(crate::errors::OmegaxProtocolError::InvalidLifecycle.into()); }
    Ok(())
}

/// Guards for `update_reserve_domain_controls`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn update_reserve_domain_controls<'info>(ctx: &mut UpdateReserveDomainControls<'info>, args: UpdateReserveDomainControlsArgs) -> Result<()> {
    // lifecycle: require status == Live
    if ctx.reserve_domain.status != Status::Live as u8 { return Err(crate::errors::OmegaxProtocolError::InvalidLifecycle.into()); }
    Ok(())
}

/// Guards for `create_domain_asset_vault`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn create_domain_asset_vault<'info>(ctx: &mut CreateDomainAssetVault<'info>, args: CreateDomainAssetVaultArgs) -> Result<()> {
    // No guards declared in spec — nothing to check.
    Ok(())
}

/// Guards for `create_health_plan`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn create_health_plan<'info>(ctx: &mut CreateHealthPlan<'info>, args: CreateHealthPlanArgs) -> Result<()> {
    // lifecycle: require status == Live
    if ctx.health_plan.status != Status::Live as u8 { return Err(crate::errors::OmegaxProtocolError::InvalidLifecycle.into()); }
    Ok(())
}

/// Guards for `update_health_plan_controls`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn update_health_plan_controls<'info>(ctx: &mut UpdateHealthPlanControls<'info>, args: UpdateHealthPlanControlsArgs) -> Result<()> {
    // lifecycle: require status == Live
    if ctx.health_plan.status != Status::Live as u8 { return Err(crate::errors::OmegaxProtocolError::InvalidLifecycle.into()); }
    Ok(())
}

/// Guards for `create_policy_series`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn create_policy_series<'info>(ctx: &mut CreatePolicySeries<'info>, args: CreatePolicySeriesArgs) -> Result<()> {
    // No guards declared in spec — nothing to check.
    Ok(())
}

/// Guards for `version_policy_series`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn version_policy_series<'info>(ctx: &mut VersionPolicySeries<'info>, args: VersionPolicySeriesArgs) -> Result<()> {
    // No guards declared in spec — nothing to check.
    Ok(())
}

/// Guards for `open_funding_line`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn open_funding_line<'info>(ctx: &mut OpenFundingLine<'info>, args: OpenFundingLineArgs) -> Result<()> {
    // No guards declared in spec — nothing to check.
    Ok(())
}

/// Guards for `fund_sponsor_budget`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn fund_sponsor_budget<'info>(ctx: &mut FundSponsorBudget<'info>, args: FundSponsorBudgetArgs) -> Result<()> {
    let emergency_pause = account_emergency_pause(&ctx.protocol_governance.to_account_info())?;
    // requires: emergency_pause = false
    if !(emergency_pause == false) { return Err(OmegaxProtocolError::ProtocolEmergencyPaused.into()); }
    // requires: args.amount > 0
    if !(args.amount > 0) { return Err(OmegaxProtocolError::AmountMustBePositive.into()); }
    Ok(())
}

/// Guards for `record_premium_payment`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn record_premium_payment<'info>(ctx: &mut RecordPremiumPayment<'info>, args: RecordPremiumPaymentArgs) -> Result<()> {
    let emergency_pause = account_emergency_pause(&ctx.protocol_governance.to_account_info())?;
    // requires: emergency_pause = false
    if !(emergency_pause == false) { return Err(OmegaxProtocolError::ProtocolEmergencyPaused.into()); }
    // requires: args.amount > 0
    if !(args.amount > 0) { return Err(OmegaxProtocolError::AmountMustBePositive.into()); }
    Ok(())
}

/// Guards for `deposit_reserve_capital`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn deposit_reserve_capital<'info>(ctx: &mut DepositReserveCapital<'info>, args: DepositReserveCapitalArgs) -> Result<()> {
    let emergency_pause = account_emergency_pause(&ctx.health_plan.to_account_info())?;
    // requires: emergency_pause = false
    if !(emergency_pause == false) { return Err(OmegaxProtocolError::ProtocolEmergencyPaused.into()); }
    // requires: args.amount > 0
    if !(args.amount > 0) { return Err(OmegaxProtocolError::AmountMustBePositive.into()); }
    Ok(())
}

/// Guards for `return_reserve_capital`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn return_reserve_capital<'info>(ctx: &mut ReturnReserveCapital<'info>, args: ReturnReserveCapitalArgs) -> Result<()> {
    let emergency_pause = account_emergency_pause(&ctx.health_plan.to_account_info())?;
    // requires: emergency_pause = false
    if !(emergency_pause == false) { return Err(OmegaxProtocolError::ProtocolEmergencyPaused.into()); }
    // requires: args.amount > 0
    if !(args.amount > 0) { return Err(OmegaxProtocolError::AmountMustBePositive.into()); }
    Ok(())
}

/// Guards for `record_reserve_earnings`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn record_reserve_earnings<'info>(ctx: &mut RecordReserveEarnings<'info>, args: RecordReserveEarningsArgs) -> Result<()> {
    let emergency_pause = account_emergency_pause(&ctx.health_plan.to_account_info())?;
    // requires: emergency_pause = false
    if !(emergency_pause == false) { return Err(OmegaxProtocolError::ProtocolEmergencyPaused.into()); }
    // requires: args.amount > 0
    if !(args.amount > 0) { return Err(OmegaxProtocolError::AmountMustBePositive.into()); }
    Ok(())
}

/// Guards for `create_obligation`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn create_obligation<'info>(ctx: &mut CreateObligation<'info>, args: CreateObligationArgs) -> Result<()> {
    let emergency_pause = account_emergency_pause(&ctx.protocol_governance.to_account_info())?;
    // requires: emergency_pause = false
    if !(emergency_pause == false) { return Err(OmegaxProtocolError::ProtocolEmergencyPaused.into()); }
    // requires: args.amount > 0
    if !(args.amount > 0) { return Err(OmegaxProtocolError::AmountMustBePositive.into()); }
    Ok(())
}

/// Guards for `reserve_obligation`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn reserve_obligation<'info>(ctx: &mut ReserveObligation<'info>, args: ReserveObligationArgs) -> Result<()> {
    let emergency_pause = account_emergency_pause(&ctx.protocol_governance.to_account_info())?;
    // requires: emergency_pause = false
    if !(emergency_pause == false) { return Err(OmegaxProtocolError::ProtocolEmergencyPaused.into()); }
    // requires: args.amount > 0
    if !(args.amount > 0) { return Err(OmegaxProtocolError::AmountMustBePositive.into()); }
    Ok(())
}

/// Guards for `settle_obligation`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn settle_obligation<'info>(ctx: &mut SettleObligation<'info>, args: SettleObligationArgs) -> Result<()> {
    let emergency_pause = account_emergency_pause(&ctx.protocol_governance.to_account_info())?;
    // requires: emergency_pause = false
    if !(emergency_pause == false) { return Err(OmegaxProtocolError::ProtocolEmergencyPaused.into()); }
    // requires: args.amount > 0
    if !(args.amount > 0) { return Err(OmegaxProtocolError::AmountMustBePositive.into()); }
    // requires: args.rail_active = true
    if !(args.rail_active == true) { return Err(OmegaxProtocolError::ReserveAssetRailInactive.into()); }
    // requires: args.rail_payout_enabled = true
    if !(args.rail_payout_enabled == true) { return Err(OmegaxProtocolError::ReserveAssetRailPayoutDisabled.into()); }
    // requires: args.rail_price_usd_1e8 > 0
    if !(args.rail_price_usd_1e8 > 0) { return Err(OmegaxProtocolError::ReserveAssetPriceInvalid.into()); }
    // requires: args.rail_max_staleness_seconds > 0
    if !(args.rail_max_staleness_seconds > 0) { return Err(OmegaxProtocolError::ReserveAssetPriceInvalid.into()); }
    // requires: args.rail_max_confidence_bps > 0
    if !(args.rail_max_confidence_bps > 0) { return Err(OmegaxProtocolError::ReserveAssetPriceInvalid.into()); }
    // requires: args.rail_last_price_confidence_bps ≤ args.rail_max_confidence_bps
    if !(args.rail_last_price_confidence_bps <= args.rail_max_confidence_bps) { return Err(OmegaxProtocolError::ReserveAssetPriceConfidenceTooWide.into()); }
    // requires: args.rail_last_price_published_at_ts > 0
    if !(args.rail_last_price_published_at_ts > 0) { return Err(OmegaxProtocolError::ReserveAssetPriceStale.into()); }
    Ok(())
}

/// Guards for `release_reserve`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn release_reserve<'info>(ctx: &mut ReleaseReserve<'info>, args: ReleaseReserveArgs) -> Result<()> {
    let emergency_pause = account_emergency_pause(&ctx.protocol_governance.to_account_info())?;
    // requires: emergency_pause = false
    if !(emergency_pause == false) { return Err(OmegaxProtocolError::ProtocolEmergencyPaused.into()); }
    // requires: args.amount > 0
    if !(args.amount > 0) { return Err(OmegaxProtocolError::AmountMustBePositive.into()); }
    Ok(())
}

/// Guards for `open_claim_case`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn open_claim_case<'info>(ctx: &mut OpenClaimCase<'info>, args: OpenClaimCaseArgs) -> Result<()> {
    let emergency_pause = account_emergency_pause(&ctx.protocol_governance.to_account_info())?;
    let active = account_active(&ctx.health_plan.to_account_info())?;
    // lifecycle: require status == Live
    if ctx.claim_case.status != Status::Live as u8 { return Err(crate::errors::OmegaxProtocolError::InvalidLifecycle.into()); }
    // requires: emergency_pause = false
    if !(emergency_pause == false) { return Err(OmegaxProtocolError::ProtocolEmergencyPaused.into()); }
    // requires: active = true
    if !(active == true) { return Err(OmegaxProtocolError::HealthPlanInactive.into()); }
    Ok(())
}

/// Guards for `authorize_claim_recipient`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn authorize_claim_recipient<'info>(ctx: &mut AuthorizeClaimRecipient<'info>, args: AuthorizeClaimRecipientArgs) -> Result<()> {
    let emergency_pause = account_emergency_pause(&ctx.protocol_governance.to_account_info())?;
    // lifecycle: require status == Live
    if ctx.claim_case.status != Status::Live as u8 { return Err(crate::errors::OmegaxProtocolError::InvalidLifecycle.into()); }
    // requires: emergency_pause = false
    if !(emergency_pause == false) { return Err(OmegaxProtocolError::ProtocolEmergencyPaused.into()); }
    Ok(())
}

/// Guards for `adjudicate_claim_case`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn adjudicate_claim_case<'info>(ctx: &mut AdjudicateClaimCase<'info>, args: AdjudicateClaimCaseArgs) -> Result<()> {
    let emergency_pause = account_emergency_pause(&ctx.protocol_governance.to_account_info())?;
    let approved_amount = account_approved_amount(&ctx.claim_case.to_account_info())?;
    // requires: emergency_pause = false
    if !(emergency_pause == false) { return Err(OmegaxProtocolError::ProtocolEmergencyPaused.into()); }
    // requires: args.reserve_amount ≤ args.approved_amount
    if !(args.reserve_amount <= args.approved_amount) { return Err(OmegaxProtocolError::AmountExceedsApprovedClaim.into()); }
    Ok(())
}

/// Guards for `settle_claim_case`.
/// Generated from the `requires` clauses of the spec handler block.
pub fn settle_claim_case<'info>(ctx: &mut SettleClaimCase<'info>, args: SettleClaimCaseArgs) -> Result<()> {
    let emergency_pause = account_emergency_pause(&ctx.protocol_governance.to_account_info())?;
    let paid_amount = account_paid_amount(&ctx.claim_case.to_account_info())?;
    let approved_amount = account_approved_amount(&ctx.claim_case.to_account_info())?;
    // requires: emergency_pause = false
    if !(emergency_pause == false) { return Err(OmegaxProtocolError::ProtocolEmergencyPaused.into()); }
    // requires: args.amount > 0
    if !(args.amount > 0) { return Err(OmegaxProtocolError::AmountMustBePositive.into()); }
    // requires: paid_amount + args.amount ≤ approved_amount
    if !(paid_amount + args.amount <= approved_amount) { return Err(OmegaxProtocolError::AmountExceedsApprovedClaim.into()); }
    // requires: args.rail_active = true
    if !(args.rail_active == true) { return Err(OmegaxProtocolError::ReserveAssetRailInactive.into()); }
    // requires: args.rail_payout_enabled = true
    if !(args.rail_payout_enabled == true) { return Err(OmegaxProtocolError::ReserveAssetRailPayoutDisabled.into()); }
    // requires: args.rail_price_usd_1e8 > 0
    if !(args.rail_price_usd_1e8 > 0) { return Err(OmegaxProtocolError::ReserveAssetPriceInvalid.into()); }
    // requires: args.rail_max_staleness_seconds > 0
    if !(args.rail_max_staleness_seconds > 0) { return Err(OmegaxProtocolError::ReserveAssetPriceInvalid.into()); }
    // requires: args.rail_max_confidence_bps > 0
    if !(args.rail_max_confidence_bps > 0) { return Err(OmegaxProtocolError::ReserveAssetPriceInvalid.into()); }
    // requires: args.rail_last_price_confidence_bps ≤ args.rail_max_confidence_bps
    if !(args.rail_last_price_confidence_bps <= args.rail_max_confidence_bps) { return Err(OmegaxProtocolError::ReserveAssetPriceConfidenceTooWide.into()); }
    // requires: args.rail_last_price_published_at_ts > 0
    if !(args.rail_last_price_published_at_ts > 0) { return Err(OmegaxProtocolError::ReserveAssetPriceStale.into()); }
    Ok(())
}

// ---- END GENERATED ----
