// ---- GENERATED BY QEDGEN — DO NOT EDIT ---- spec-hash:149a1494f4899147
#![allow(unexpected_cfgs)]

use anchor_lang::prelude::*;

mod instructions;
pub mod errors;
pub mod state;
pub mod guards;

declare_id!("6EXiDfGVbG7V1X2xaEALDZ7CtSuezkM8ZvXXFpk5WxQM");

#[program]
pub mod omegaxprotocol {
    use super::*;

    pub fn initialize_protocol_governance(ctx: Context<InitializeProtocolGovernance>, args: InitializeProtocolGovernanceArgs) -> Result<()> {
        ctx.accounts.handler(args)
    }

    pub fn set_protocol_emergency_pause(ctx: Context<SetProtocolEmergencyPause>, args: SetProtocolEmergencyPauseArgs) -> Result<()> {
        ctx.accounts.handler(args)
    }

    pub fn rotate_protocol_governance_authority(ctx: Context<RotateProtocolGovernanceAuthority>, args: RotateProtocolGovernanceAuthorityArgs) -> Result<()> {
        ctx.accounts.handler(args)
    }

    pub fn accept_protocol_governance_authority(ctx: Context<AcceptProtocolGovernanceAuthority>) -> Result<()> {
        ctx.accounts.handler()
    }

    pub fn cancel_protocol_governance_authority_transfer(ctx: Context<CancelProtocolGovernanceAuthorityTransfer>) -> Result<()> {
        ctx.accounts.handler()
    }

    pub fn create_reserve_domain(ctx: Context<CreateReserveDomain>, args: CreateReserveDomainArgs) -> Result<()> {
        ctx.accounts.handler(args)
    }

    pub fn update_reserve_domain_controls(ctx: Context<UpdateReserveDomainControls>, args: UpdateReserveDomainControlsArgs) -> Result<()> {
        ctx.accounts.handler(args)
    }

    pub fn create_domain_asset_vault(ctx: Context<CreateDomainAssetVault>, args: CreateDomainAssetVaultArgs) -> Result<()> {
        ctx.accounts.handler(args)
    }

    pub fn configure_reserve_asset_rail(ctx: Context<ConfigureReserveAssetRail>, args: ConfigureReserveAssetRailArgs) -> Result<()> {
        ctx.accounts.handler(args)
    }

    pub fn publish_reserve_asset_rail_price(ctx: Context<PublishReserveAssetRailPrice>, args: PublishReserveAssetRailPriceArgs) -> Result<()> {
        ctx.accounts.handler(args)
    }

    pub fn init_protocol_fee_vault(ctx: Context<InitProtocolFeeVault>, args: InitProtocolFeeVaultArgs) -> Result<()> {
        ctx.accounts.handler(args)
    }

    pub fn init_pool_treasury_vault(ctx: Context<InitPoolTreasuryVault>, args: InitPoolTreasuryVaultArgs) -> Result<()> {
        ctx.accounts.handler(args)
    }

    pub fn init_pool_oracle_fee_vault(ctx: Context<InitPoolOracleFeeVault>, args: InitPoolOracleFeeVaultArgs) -> Result<()> {
        ctx.accounts.handler(args)
    }

    pub fn create_health_plan(ctx: Context<CreateHealthPlan>, args: CreateHealthPlanArgs) -> Result<()> {
        ctx.accounts.handler(args)
    }

    pub fn update_health_plan_controls(ctx: Context<UpdateHealthPlanControls>, args: UpdateHealthPlanControlsArgs) -> Result<()> {
        ctx.accounts.handler(args)
    }

    pub fn create_policy_series(ctx: Context<CreatePolicySeries>, args: CreatePolicySeriesArgs) -> Result<()> {
        ctx.accounts.handler(args)
    }

    pub fn initialize_series_reserve_ledger(ctx: Context<InitializeSeriesReserveLedger>, args: InitializeSeriesReserveLedgerArgs) -> Result<()> {
        ctx.accounts.handler(args)
    }

    pub fn version_policy_series(ctx: Context<VersionPolicySeries>, args: VersionPolicySeriesArgs) -> Result<()> {
        ctx.accounts.handler(args)
    }

    pub fn open_member_position(ctx: Context<OpenMemberPosition>, args: OpenMemberPositionArgs) -> Result<()> {
        ctx.accounts.handler(args)
    }

    pub fn update_member_eligibility(ctx: Context<UpdateMemberEligibility>, args: UpdateMemberEligibilityArgs) -> Result<()> {
        ctx.accounts.handler(args)
    }

    pub fn open_funding_line(ctx: Context<OpenFundingLine>, args: OpenFundingLineArgs) -> Result<()> {
        ctx.accounts.handler(args)
    }

    pub fn fund_sponsor_budget(ctx: Context<FundSponsorBudget>, args: FundSponsorBudgetArgs) -> Result<()> {
        ctx.accounts.handler(args)
    }

    pub fn record_premium_payment(ctx: Context<RecordPremiumPayment>, args: RecordPremiumPaymentArgs) -> Result<()> {
        ctx.accounts.handler(args)
    }

    pub fn create_obligation(ctx: Context<CreateObligation>, args: CreateObligationArgs) -> Result<()> {
        ctx.accounts.handler(args)
    }

    pub fn reserve_obligation(ctx: Context<ReserveObligation>, args: ReserveObligationArgs) -> Result<()> {
        ctx.accounts.handler(args)
    }

    pub fn settle_obligation(ctx: Context<SettleObligation>, args: SettleObligationArgs) -> Result<()> {
        ctx.accounts.handler(args)
    }

    pub fn release_reserve(ctx: Context<ReleaseReserve>, args: ReleaseReserveArgs) -> Result<()> {
        ctx.accounts.handler(args)
    }

    pub fn open_claim_case(ctx: Context<OpenClaimCase>, args: OpenClaimCaseArgs) -> Result<()> {
        ctx.accounts.handler(args)
    }

    pub fn authorize_claim_recipient(ctx: Context<AuthorizeClaimRecipient>, args: AuthorizeClaimRecipientArgs) -> Result<()> {
        ctx.accounts.handler(args)
    }

    pub fn attach_claim_evidence_ref(ctx: Context<AttachClaimEvidenceRef>, args: AttachClaimEvidenceRefArgs) -> Result<()> {
        ctx.accounts.handler(args)
    }

    pub fn adjudicate_claim_case(ctx: Context<AdjudicateClaimCase>, args: AdjudicateClaimCaseArgs) -> Result<()> {
        ctx.accounts.handler(args)
    }

    pub fn settle_claim_case(ctx: Context<SettleClaimCase>, args: SettleClaimCaseArgs) -> Result<()> {
        ctx.accounts.handler(args)
    }

    pub fn settle_claim_case_selected_asset(ctx: Context<SettleClaimCaseSelectedAsset>, args: SettleClaimCaseSelectedAssetArgs) -> Result<()> {
        ctx.accounts.handler(args)
    }

    pub fn create_liquidity_pool(ctx: Context<CreateLiquidityPool>, args: CreateLiquidityPoolArgs) -> Result<()> {
        ctx.accounts.handler(args)
    }

    pub fn create_capital_class(ctx: Context<CreateCapitalClass>, args: CreateCapitalClassArgs) -> Result<()> {
        ctx.accounts.handler(args)
    }

    pub fn update_capital_class_controls(ctx: Context<UpdateCapitalClassControls>, args: UpdateCapitalClassControlsArgs) -> Result<()> {
        ctx.accounts.handler(args)
    }

    pub fn update_lp_position_credentialing(ctx: Context<UpdateLpPositionCredentialing>, args: UpdateLpPositionCredentialingArgs) -> Result<()> {
        ctx.accounts.handler(args)
    }

    pub fn deposit_into_capital_class(ctx: Context<DepositIntoCapitalClass>, args: DepositIntoCapitalClassArgs) -> Result<()> {
        ctx.accounts.handler(args)
    }

    pub fn request_redemption(ctx: Context<RequestRedemption>, args: RequestRedemptionArgs) -> Result<()> {
        ctx.accounts.handler(args)
    }

    pub fn process_redemption_queue(ctx: Context<ProcessRedemptionQueue>, args: ProcessRedemptionQueueArgs) -> Result<()> {
        ctx.accounts.handler(args)
    }

    pub fn withdraw_protocol_fee_spl(ctx: Context<WithdrawProtocolFeeSpl>, args: WithdrawArgs) -> Result<()> {
        ctx.accounts.handler(args)
    }

    pub fn withdraw_protocol_fee_sol(ctx: Context<WithdrawProtocolFeeSol>, args: WithdrawArgs) -> Result<()> {
        ctx.accounts.handler(args)
    }

    pub fn withdraw_pool_treasury_spl(ctx: Context<WithdrawPoolTreasurySpl>, args: WithdrawArgs) -> Result<()> {
        ctx.accounts.handler(args)
    }

    pub fn withdraw_pool_treasury_sol(ctx: Context<WithdrawPoolTreasurySol>, args: WithdrawArgs) -> Result<()> {
        ctx.accounts.handler(args)
    }

    pub fn withdraw_pool_oracle_fee_spl(ctx: Context<WithdrawPoolOracleFeeSpl>, args: WithdrawArgs) -> Result<()> {
        ctx.accounts.handler(args)
    }

    pub fn withdraw_pool_oracle_fee_sol(ctx: Context<WithdrawPoolOracleFeeSol>, args: WithdrawArgs) -> Result<()> {
        ctx.accounts.handler(args)
    }

    pub fn create_allocation_position(ctx: Context<CreateAllocationPosition>, args: CreateAllocationPositionArgs) -> Result<()> {
        ctx.accounts.handler(args)
    }

    pub fn update_allocation_caps(ctx: Context<UpdateAllocationCaps>, args: UpdateAllocationCapsArgs) -> Result<()> {
        ctx.accounts.handler(args)
    }

    pub fn allocate_capital(ctx: Context<AllocateCapital>, args: AllocateCapitalArgs) -> Result<()> {
        ctx.accounts.handler(args)
    }

    pub fn deallocate_capital(ctx: Context<DeallocateCapital>, args: DeallocateCapitalArgs) -> Result<()> {
        ctx.accounts.handler(args)
    }

    pub fn mark_impairment(ctx: Context<MarkImpairment>, args: MarkImpairmentArgs) -> Result<()> {
        ctx.accounts.handler(args)
    }

    pub fn register_oracle(ctx: Context<RegisterOracle>, args: RegisterOracleArgs) -> Result<()> {
        ctx.accounts.handler(args)
    }

    pub fn claim_oracle(ctx: Context<ClaimOracle>) -> Result<()> {
        ctx.accounts.handler()
    }

    pub fn update_oracle_profile(ctx: Context<UpdateOracleProfile>, args: UpdateOracleProfileArgs) -> Result<()> {
        ctx.accounts.handler(args)
    }

    pub fn set_pool_oracle(ctx: Context<SetPoolOracle>, args: SetPoolOracleArgs) -> Result<()> {
        ctx.accounts.handler(args)
    }

    pub fn set_pool_oracle_permissions(ctx: Context<SetPoolOraclePermissions>, args: SetPoolOraclePermissionsArgs) -> Result<()> {
        ctx.accounts.handler(args)
    }

    pub fn set_pool_oracle_policy(ctx: Context<SetPoolOraclePolicy>, args: SetPoolOraclePolicyArgs) -> Result<()> {
        ctx.accounts.handler(args)
    }

    pub fn register_outcome_schema(ctx: Context<RegisterOutcomeSchema>, args: RegisterOutcomeSchemaArgs) -> Result<()> {
        ctx.accounts.handler(args)
    }

    pub fn verify_outcome_schema(ctx: Context<VerifyOutcomeSchema>, args: VerifyOutcomeSchemaArgs) -> Result<()> {
        ctx.accounts.handler(args)
    }

    pub fn backfill_schema_dependency_ledger(ctx: Context<BackfillSchemaDependencyLedger>, args: BackfillSchemaDependencyLedgerArgs) -> Result<()> {
        ctx.accounts.handler(args)
    }

    pub fn close_outcome_schema(ctx: Context<CloseOutcomeSchema>) -> Result<()> {
        ctx.accounts.handler()
    }

    pub fn attest_claim_case(ctx: Context<AttestClaimCase>, args: AttestClaimCaseArgs) -> Result<()> {
        ctx.accounts.handler(args)
    }

}

// `#[derive(Accounts)]` structs live at the crate root so the
// Anchor `#[program]` macro can resolve them via `crate::*`.
// The handler impl blocks live next to the (always-regenerated)
// guard module in `instructions/<name>.rs`.
use crate::state::*;
use anchor_spl::token::Token;

#[derive(Accounts)]
pub struct InitializeProtocolGovernance<'info> {
    #[account(mut)]
    pub governance_authority: Signer<'info>,
    #[account(mut, has_one = governance_authority)]
    pub protocol_governance: Account<'info, OmegaxProtocolAccount>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct SetProtocolEmergencyPause<'info> {
    pub authority: Signer<'info>,
    #[account(mut, has_one = authority)]
    pub protocol_governance: Account<'info, OmegaxProtocolAccount>,
}

#[derive(Accounts)]
pub struct RotateProtocolGovernanceAuthority<'info> {
    pub authority: Signer<'info>,
    #[account(mut, has_one = authority)]
    pub protocol_governance: Account<'info, OmegaxProtocolAccount>,
}

#[derive(Accounts)]
pub struct AcceptProtocolGovernanceAuthority<'info> {
    pub pending_authority: Signer<'info>,
    #[account(mut, has_one = pending_authority)]
    pub protocol_governance: Account<'info, OmegaxProtocolAccount>,
}

#[derive(Accounts)]
pub struct CancelProtocolGovernanceAuthorityTransfer<'info> {
    pub authority: Signer<'info>,
    #[account(mut, has_one = authority)]
    pub protocol_governance: Account<'info, OmegaxProtocolAccount>,
}

#[derive(Accounts)]
pub struct CreateReserveDomain<'info> {
    #[account(mut)]
    pub authority: Signer<'info>,
    pub protocol_governance: AccountInfo<'info>,
    #[account(mut, has_one = authority)]
    pub reserve_domain: Account<'info, OmegaxProtocolAccount>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct UpdateReserveDomainControls<'info> {
    pub authority: Signer<'info>,
    pub protocol_governance: AccountInfo<'info>,
    #[account(mut, has_one = authority)]
    pub reserve_domain: Account<'info, OmegaxProtocolAccount>,
}

#[derive(Accounts)]
pub struct CreateDomainAssetVault<'info> {
    #[account(mut)]
    pub authority: Signer<'info>,
    pub protocol_governance: AccountInfo<'info>,
    #[account(mut)]
    pub reserve_domain: AccountInfo<'info>,
    #[account(mut)]
    pub domain_asset_vault: AccountInfo<'info>,
    #[account(mut)]
    pub domain_asset_ledger: AccountInfo<'info>,
    pub asset_mint: AccountInfo<'info>,
    #[account(mut)]
    pub vault_token_account: AccountInfo<'info>,
    pub token_program: Program<'info, Token>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct ConfigureReserveAssetRail<'info> {
    #[account(mut)]
    pub authority: Signer<'info>,
    pub protocol_governance: AccountInfo<'info>,
    pub reserve_domain: AccountInfo<'info>,
    #[account(mut, has_one = authority)]
    pub reserve_asset_rail: Account<'info, OmegaxProtocolAccount>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct PublishReserveAssetRailPrice<'info> {
    pub authority: Signer<'info>,
    pub protocol_governance: AccountInfo<'info>,
    #[account(mut, has_one = authority)]
    pub reserve_asset_rail: Account<'info, OmegaxProtocolAccount>,
}

#[derive(Accounts)]
pub struct InitProtocolFeeVault<'info> {
    #[account(mut)]
    pub authority: Signer<'info>,
    pub protocol_governance: AccountInfo<'info>,
    pub reserve_domain: AccountInfo<'info>,
    pub domain_asset_vault: AccountInfo<'info>,
    #[account(mut, has_one = authority)]
    pub protocol_fee_vault: Account<'info, OmegaxProtocolAccount>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct InitPoolTreasuryVault<'info> {
    #[account(mut)]
    pub authority: Signer<'info>,
    pub protocol_governance: AccountInfo<'info>,
    pub liquidity_pool: AccountInfo<'info>,
    pub domain_asset_vault: AccountInfo<'info>,
    #[account(mut, has_one = authority)]
    pub pool_treasury_vault: Account<'info, OmegaxProtocolAccount>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct InitPoolOracleFeeVault<'info> {
    #[account(mut)]
    pub authority: Signer<'info>,
    pub protocol_governance: AccountInfo<'info>,
    pub liquidity_pool: AccountInfo<'info>,
    pub oracle_profile: AccountInfo<'info>,
    pub pool_oracle_approval: AccountInfo<'info>,
    pub domain_asset_vault: AccountInfo<'info>,
    #[account(mut, has_one = authority)]
    pub pool_oracle_fee_vault: Account<'info, OmegaxProtocolAccount>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct CreateHealthPlan<'info> {
    #[account(mut)]
    pub plan_admin: Signer<'info>,
    pub protocol_governance: AccountInfo<'info>,
    pub reserve_domain: AccountInfo<'info>,
    #[account(mut, has_one = plan_admin)]
    pub health_plan: Account<'info, OmegaxProtocolAccount>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct UpdateHealthPlanControls<'info> {
    pub authority: Signer<'info>,
    pub protocol_governance: AccountInfo<'info>,
    #[account(mut, has_one = authority)]
    pub health_plan: Account<'info, OmegaxProtocolAccount>,
}

#[derive(Accounts)]
pub struct CreatePolicySeries<'info> {
    #[account(mut)]
    pub authority: Signer<'info>,
    pub protocol_governance: AccountInfo<'info>,
    pub health_plan: AccountInfo<'info>,
    #[account(mut)]
    pub policy_series: AccountInfo<'info>,
    #[account(mut)]
    pub series_reserve_ledger: AccountInfo<'info>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct InitializeSeriesReserveLedger<'info> {
    #[account(mut)]
    pub authority: Signer<'info>,
    pub protocol_governance: AccountInfo<'info>,
    pub health_plan: AccountInfo<'info>,
    pub policy_series: AccountInfo<'info>,
    #[account(mut, has_one = authority)]
    pub series_reserve_ledger: Account<'info, OmegaxProtocolAccount>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct VersionPolicySeries<'info> {
    #[account(mut)]
    pub authority: Signer<'info>,
    pub protocol_governance: AccountInfo<'info>,
    pub health_plan: AccountInfo<'info>,
    #[account(mut)]
    pub current_policy_series: AccountInfo<'info>,
    #[account(mut)]
    pub next_policy_series: AccountInfo<'info>,
    #[account(mut)]
    pub next_series_reserve_ledger: AccountInfo<'info>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct OpenMemberPosition<'info> {
    #[account(mut)]
    pub wallet: Signer<'info>,
    pub protocol_governance: AccountInfo<'info>,
    pub health_plan: AccountInfo<'info>,
    #[account(mut)]
    pub member_position: AccountInfo<'info>,
    #[account(mut)]
    pub membership_anchor_seat: AccountInfo<'info>,
    pub token_gate_account: AccountInfo<'info>,
    pub invite_authority: Signer<'info>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct UpdateMemberEligibility<'info> {
    pub authority: Signer<'info>,
    pub protocol_governance: AccountInfo<'info>,
    pub health_plan: AccountInfo<'info>,
    #[account(mut, has_one = authority)]
    pub member_position: Account<'info, OmegaxProtocolAccount>,
    pub membership_anchor_seat: AccountInfo<'info>,
}

#[derive(Accounts)]
pub struct OpenFundingLine<'info> {
    #[account(mut)]
    pub authority: Signer<'info>,
    pub protocol_governance: AccountInfo<'info>,
    pub health_plan: AccountInfo<'info>,
    pub domain_asset_vault: AccountInfo<'info>,
    #[account(mut)]
    pub domain_asset_ledger: AccountInfo<'info>,
    #[account(mut)]
    pub funding_line: AccountInfo<'info>,
    #[account(mut)]
    pub funding_line_ledger: AccountInfo<'info>,
    #[account(mut)]
    pub plan_reserve_ledger: AccountInfo<'info>,
    #[account(mut)]
    pub series_reserve_ledger: AccountInfo<'info>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct FundSponsorBudget<'info> {
    pub authority: Signer<'info>,
    pub protocol_governance: AccountInfo<'info>,
    pub health_plan: AccountInfo<'info>,
    #[account(mut)]
    pub domain_asset_vault: AccountInfo<'info>,
    #[account(mut)]
    pub domain_asset_ledger: AccountInfo<'info>,
    #[account(mut)]
    pub funding_line: AccountInfo<'info>,
    #[account(mut)]
    pub funding_line_ledger: AccountInfo<'info>,
    #[account(mut)]
    pub plan_reserve_ledger: AccountInfo<'info>,
    #[account(mut)]
    pub series_reserve_ledger: AccountInfo<'info>,
    #[account(mut)]
    pub source_token_account: AccountInfo<'info>,
    pub asset_mint: AccountInfo<'info>,
    #[account(mut)]
    pub vault_token_account: AccountInfo<'info>,
    pub token_program: Program<'info, Token>,
}

#[derive(Accounts)]
pub struct RecordPremiumPayment<'info> {
    pub authority: Signer<'info>,
    pub protocol_governance: AccountInfo<'info>,
    pub health_plan: AccountInfo<'info>,
    #[account(mut)]
    pub domain_asset_vault: AccountInfo<'info>,
    #[account(mut)]
    pub domain_asset_ledger: AccountInfo<'info>,
    #[account(mut)]
    pub funding_line: AccountInfo<'info>,
    #[account(mut)]
    pub funding_line_ledger: AccountInfo<'info>,
    #[account(mut)]
    pub plan_reserve_ledger: AccountInfo<'info>,
    #[account(mut)]
    pub series_reserve_ledger: AccountInfo<'info>,
    #[account(mut)]
    pub protocol_fee_vault: AccountInfo<'info>,
    #[account(mut)]
    pub source_token_account: AccountInfo<'info>,
    pub asset_mint: AccountInfo<'info>,
    #[account(mut)]
    pub vault_token_account: AccountInfo<'info>,
    pub token_program: Program<'info, Token>,
}

#[derive(Accounts)]
pub struct CreateObligation<'info> {
    #[account(mut)]
    pub authority: Signer<'info>,
    pub protocol_governance: AccountInfo<'info>,
    pub health_plan: AccountInfo<'info>,
    #[account(mut)]
    pub domain_asset_ledger: AccountInfo<'info>,
    #[account(mut)]
    pub funding_line: AccountInfo<'info>,
    #[account(mut)]
    pub funding_line_ledger: AccountInfo<'info>,
    #[account(mut)]
    pub plan_reserve_ledger: AccountInfo<'info>,
    #[account(mut)]
    pub series_reserve_ledger: AccountInfo<'info>,
    #[account(mut)]
    pub pool_class_ledger: AccountInfo<'info>,
    #[account(mut)]
    pub allocation_ledger: AccountInfo<'info>,
    #[account(mut)]
    pub obligation: AccountInfo<'info>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct ReserveObligation<'info> {
    pub authority: Signer<'info>,
    pub protocol_governance: AccountInfo<'info>,
    pub health_plan: AccountInfo<'info>,
    #[account(mut)]
    pub domain_asset_ledger: AccountInfo<'info>,
    #[account(mut)]
    pub funding_line: AccountInfo<'info>,
    #[account(mut)]
    pub funding_line_ledger: AccountInfo<'info>,
    #[account(mut)]
    pub plan_reserve_ledger: AccountInfo<'info>,
    #[account(mut)]
    pub series_reserve_ledger: AccountInfo<'info>,
    #[account(mut)]
    pub pool_class_ledger: AccountInfo<'info>,
    #[account(mut)]
    pub allocation_position: AccountInfo<'info>,
    #[account(mut)]
    pub allocation_ledger: AccountInfo<'info>,
    #[account(mut)]
    pub obligation: AccountInfo<'info>,
    #[account(mut)]
    pub claim_case: AccountInfo<'info>,
}

#[derive(Accounts)]
pub struct SettleObligation<'info> {
    pub authority: Signer<'info>,
    pub protocol_governance: AccountInfo<'info>,
    pub health_plan: AccountInfo<'info>,
    pub reserve_asset_rail: AccountInfo<'info>,
    #[account(mut)]
    pub domain_asset_vault: AccountInfo<'info>,
    #[account(mut)]
    pub domain_asset_ledger: AccountInfo<'info>,
    #[account(mut)]
    pub funding_line: AccountInfo<'info>,
    #[account(mut)]
    pub funding_line_ledger: AccountInfo<'info>,
    #[account(mut)]
    pub plan_reserve_ledger: AccountInfo<'info>,
    #[account(mut)]
    pub series_reserve_ledger: AccountInfo<'info>,
    #[account(mut)]
    pub pool_class_ledger: AccountInfo<'info>,
    #[account(mut)]
    pub allocation_position: AccountInfo<'info>,
    #[account(mut)]
    pub allocation_ledger: AccountInfo<'info>,
    #[account(mut)]
    pub obligation: AccountInfo<'info>,
    #[account(mut)]
    pub claim_case: AccountInfo<'info>,
    pub member_position: AccountInfo<'info>,
    pub asset_mint: AccountInfo<'info>,
    #[account(mut)]
    pub vault_token_account: AccountInfo<'info>,
    #[account(mut)]
    pub recipient_token_account: AccountInfo<'info>,
    pub token_program: Program<'info, Token>,
    #[account(mut)]
    pub pool_oracle_fee_vault: AccountInfo<'info>,
    pub pool_oracle_policy: AccountInfo<'info>,
    pub oracle_fee_attestation: AccountInfo<'info>,
}

#[derive(Accounts)]
pub struct ReleaseReserve<'info> {
    pub authority: Signer<'info>,
    pub protocol_governance: AccountInfo<'info>,
    pub health_plan: AccountInfo<'info>,
    #[account(mut)]
    pub domain_asset_ledger: AccountInfo<'info>,
    #[account(mut)]
    pub funding_line: AccountInfo<'info>,
    #[account(mut)]
    pub funding_line_ledger: AccountInfo<'info>,
    #[account(mut)]
    pub plan_reserve_ledger: AccountInfo<'info>,
    #[account(mut)]
    pub series_reserve_ledger: AccountInfo<'info>,
    #[account(mut)]
    pub pool_class_ledger: AccountInfo<'info>,
    #[account(mut)]
    pub allocation_position: AccountInfo<'info>,
    #[account(mut)]
    pub allocation_ledger: AccountInfo<'info>,
    #[account(mut)]
    pub obligation: AccountInfo<'info>,
    #[account(mut)]
    pub claim_case: AccountInfo<'info>,
}

#[derive(Accounts)]
pub struct OpenClaimCase<'info> {
    #[account(mut)]
    pub authority: Signer<'info>,
    pub protocol_governance: AccountInfo<'info>,
    pub health_plan: AccountInfo<'info>,
    pub member_position: AccountInfo<'info>,
    pub funding_line: AccountInfo<'info>,
    #[account(mut, has_one = authority)]
    pub claim_case: Account<'info, OmegaxProtocolAccount>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct AuthorizeClaimRecipient<'info> {
    pub authority: Signer<'info>,
    pub protocol_governance: AccountInfo<'info>,
    pub member_position: AccountInfo<'info>,
    #[account(mut, has_one = authority)]
    pub claim_case: Account<'info, OmegaxProtocolAccount>,
}

#[derive(Accounts)]
pub struct AttachClaimEvidenceRef<'info> {
    pub authority: Signer<'info>,
    pub protocol_governance: AccountInfo<'info>,
    pub health_plan: AccountInfo<'info>,
    #[account(mut, has_one = authority)]
    pub claim_case: Account<'info, OmegaxProtocolAccount>,
}

#[derive(Accounts)]
pub struct AdjudicateClaimCase<'info> {
    pub authority: Signer<'info>,
    pub protocol_governance: AccountInfo<'info>,
    pub health_plan: AccountInfo<'info>,
    #[account(mut)]
    pub claim_case: AccountInfo<'info>,
    #[account(mut)]
    pub obligation: AccountInfo<'info>,
}

#[derive(Accounts)]
pub struct SettleClaimCase<'info> {
    pub authority: Signer<'info>,
    pub protocol_governance: AccountInfo<'info>,
    pub health_plan: AccountInfo<'info>,
    pub reserve_asset_rail: AccountInfo<'info>,
    #[account(mut)]
    pub domain_asset_vault: AccountInfo<'info>,
    #[account(mut)]
    pub domain_asset_ledger: AccountInfo<'info>,
    #[account(mut)]
    pub funding_line: AccountInfo<'info>,
    #[account(mut)]
    pub funding_line_ledger: AccountInfo<'info>,
    #[account(mut)]
    pub plan_reserve_ledger: AccountInfo<'info>,
    #[account(mut)]
    pub series_reserve_ledger: AccountInfo<'info>,
    #[account(mut)]
    pub pool_class_ledger: AccountInfo<'info>,
    #[account(mut)]
    pub allocation_position: AccountInfo<'info>,
    #[account(mut)]
    pub allocation_ledger: AccountInfo<'info>,
    #[account(mut)]
    pub claim_case: AccountInfo<'info>,
    #[account(mut)]
    pub obligation: AccountInfo<'info>,
    #[account(mut)]
    pub protocol_fee_vault: AccountInfo<'info>,
    #[account(mut)]
    pub pool_oracle_fee_vault: AccountInfo<'info>,
    pub pool_oracle_policy: AccountInfo<'info>,
    pub oracle_fee_attestation: AccountInfo<'info>,
    pub member_position: AccountInfo<'info>,
    pub asset_mint: AccountInfo<'info>,
    #[account(mut)]
    pub vault_token_account: AccountInfo<'info>,
    #[account(mut)]
    pub recipient_token_account: AccountInfo<'info>,
    pub token_program: Program<'info, Token>,
}

#[derive(Accounts)]
pub struct SettleClaimCaseSelectedAsset<'info> {
    pub authority: Signer<'info>,
    pub protocol_governance: AccountInfo<'info>,
    pub health_plan: AccountInfo<'info>,
    pub claim_asset_rail: AccountInfo<'info>,
    pub payout_asset_rail: AccountInfo<'info>,
    #[account(mut)]
    pub payout_domain_asset_vault: AccountInfo<'info>,
    #[account(mut)]
    pub payout_domain_asset_ledger: AccountInfo<'info>,
    #[account(mut)]
    pub payout_funding_line: AccountInfo<'info>,
    #[account(mut)]
    pub payout_funding_line_ledger: AccountInfo<'info>,
    #[account(mut)]
    pub payout_plan_reserve_ledger: AccountInfo<'info>,
    #[account(mut)]
    pub payout_series_reserve_ledger: AccountInfo<'info>,
    #[account(mut)]
    pub claim_case: AccountInfo<'info>,
    pub member_position: AccountInfo<'info>,
    pub claim_asset_mint: AccountInfo<'info>,
    pub payout_asset_mint: AccountInfo<'info>,
    #[account(mut)]
    pub payout_vault_token_account: AccountInfo<'info>,
    #[account(mut)]
    pub recipient_token_account: AccountInfo<'info>,
    pub token_program: Program<'info, Token>,
}

#[derive(Accounts)]
pub struct CreateLiquidityPool<'info> {
    #[account(mut)]
    pub authority: Signer<'info>,
    pub protocol_governance: AccountInfo<'info>,
    pub reserve_domain: AccountInfo<'info>,
    pub domain_asset_vault: AccountInfo<'info>,
    #[account(mut, has_one = authority)]
    pub liquidity_pool: Account<'info, OmegaxProtocolAccount>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct CreateCapitalClass<'info> {
    #[account(mut)]
    pub authority: Signer<'info>,
    pub protocol_governance: AccountInfo<'info>,
    pub liquidity_pool: AccountInfo<'info>,
    #[account(mut)]
    pub capital_class: AccountInfo<'info>,
    #[account(mut)]
    pub pool_class_ledger: AccountInfo<'info>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct UpdateCapitalClassControls<'info> {
    pub authority: Signer<'info>,
    pub protocol_governance: AccountInfo<'info>,
    pub liquidity_pool: AccountInfo<'info>,
    #[account(mut, has_one = authority)]
    pub capital_class: Account<'info, OmegaxProtocolAccount>,
}

#[derive(Accounts)]
pub struct UpdateLpPositionCredentialing<'info> {
    #[account(mut)]
    pub authority: Signer<'info>,
    pub protocol_governance: AccountInfo<'info>,
    pub liquidity_pool: AccountInfo<'info>,
    pub capital_class: AccountInfo<'info>,
    #[account(mut, has_one = authority)]
    pub lp_position: Account<'info, OmegaxProtocolAccount>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct DepositIntoCapitalClass<'info> {
    #[account(mut)]
    pub owner: Signer<'info>,
    pub protocol_governance: AccountInfo<'info>,
    #[account(mut)]
    pub domain_asset_vault: AccountInfo<'info>,
    #[account(mut)]
    pub domain_asset_ledger: AccountInfo<'info>,
    #[account(mut)]
    pub liquidity_pool: AccountInfo<'info>,
    #[account(mut)]
    pub capital_class: AccountInfo<'info>,
    #[account(mut)]
    pub pool_class_ledger: AccountInfo<'info>,
    #[account(mut)]
    pub lp_position: AccountInfo<'info>,
    #[account(mut)]
    pub pool_treasury_vault: AccountInfo<'info>,
    #[account(mut)]
    pub source_token_account: AccountInfo<'info>,
    pub asset_mint: AccountInfo<'info>,
    #[account(mut)]
    pub vault_token_account: AccountInfo<'info>,
    pub token_program: Program<'info, Token>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct RequestRedemption<'info> {
    pub owner: Signer<'info>,
    pub protocol_governance: AccountInfo<'info>,
    #[account(mut)]
    pub liquidity_pool: AccountInfo<'info>,
    #[account(mut)]
    pub capital_class: AccountInfo<'info>,
    #[account(mut)]
    pub pool_class_ledger: AccountInfo<'info>,
    #[account(mut)]
    pub domain_asset_ledger: AccountInfo<'info>,
    #[account(mut)]
    pub lp_position: AccountInfo<'info>,
}

#[derive(Accounts)]
pub struct ProcessRedemptionQueue<'info> {
    pub authority: Signer<'info>,
    pub protocol_governance: AccountInfo<'info>,
    #[account(mut)]
    pub domain_asset_vault: AccountInfo<'info>,
    #[account(mut)]
    pub domain_asset_ledger: AccountInfo<'info>,
    #[account(mut)]
    pub liquidity_pool: AccountInfo<'info>,
    #[account(mut)]
    pub capital_class: AccountInfo<'info>,
    #[account(mut)]
    pub pool_class_ledger: AccountInfo<'info>,
    #[account(mut)]
    pub lp_position: AccountInfo<'info>,
    #[account(mut)]
    pub pool_treasury_vault: AccountInfo<'info>,
    pub asset_mint: AccountInfo<'info>,
    #[account(mut)]
    pub vault_token_account: AccountInfo<'info>,
    #[account(mut)]
    pub recipient_token_account: AccountInfo<'info>,
    pub token_program: Program<'info, Token>,
}

#[derive(Accounts)]
pub struct WithdrawProtocolFeeSpl<'info> {
    pub authority: Signer<'info>,
    pub protocol_governance: AccountInfo<'info>,
    pub reserve_domain: AccountInfo<'info>,
    #[account(mut)]
    pub protocol_fee_vault: AccountInfo<'info>,
    #[account(mut)]
    pub domain_asset_vault: AccountInfo<'info>,
    #[account(mut)]
    pub domain_asset_ledger: AccountInfo<'info>,
    pub asset_mint: AccountInfo<'info>,
    #[account(mut)]
    pub vault_token_account: AccountInfo<'info>,
    #[account(mut)]
    pub recipient_token_account: AccountInfo<'info>,
    pub token_program: Program<'info, Token>,
}

#[derive(Accounts)]
pub struct WithdrawProtocolFeeSol<'info> {
    pub authority: Signer<'info>,
    pub protocol_governance: AccountInfo<'info>,
    pub reserve_domain: AccountInfo<'info>,
    #[account(mut)]
    pub protocol_fee_vault: AccountInfo<'info>,
    #[account(mut)]
    pub recipient: AccountInfo<'info>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct WithdrawPoolTreasurySpl<'info> {
    pub authority: Signer<'info>,
    pub protocol_governance: AccountInfo<'info>,
    pub liquidity_pool: AccountInfo<'info>,
    #[account(mut)]
    pub pool_treasury_vault: AccountInfo<'info>,
    #[account(mut)]
    pub domain_asset_vault: AccountInfo<'info>,
    #[account(mut)]
    pub domain_asset_ledger: AccountInfo<'info>,
    pub asset_mint: AccountInfo<'info>,
    #[account(mut)]
    pub vault_token_account: AccountInfo<'info>,
    #[account(mut)]
    pub recipient_token_account: AccountInfo<'info>,
    pub token_program: Program<'info, Token>,
}

#[derive(Accounts)]
pub struct WithdrawPoolTreasurySol<'info> {
    pub authority: Signer<'info>,
    pub protocol_governance: AccountInfo<'info>,
    pub liquidity_pool: AccountInfo<'info>,
    #[account(mut)]
    pub pool_treasury_vault: AccountInfo<'info>,
    #[account(mut)]
    pub recipient: AccountInfo<'info>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct WithdrawPoolOracleFeeSpl<'info> {
    pub authority: Signer<'info>,
    pub protocol_governance: AccountInfo<'info>,
    pub liquidity_pool: AccountInfo<'info>,
    pub oracle_profile: AccountInfo<'info>,
    #[account(mut)]
    pub pool_oracle_fee_vault: AccountInfo<'info>,
    #[account(mut)]
    pub domain_asset_vault: AccountInfo<'info>,
    #[account(mut)]
    pub domain_asset_ledger: AccountInfo<'info>,
    pub asset_mint: AccountInfo<'info>,
    #[account(mut)]
    pub vault_token_account: AccountInfo<'info>,
    #[account(mut)]
    pub recipient_token_account: AccountInfo<'info>,
    pub token_program: Program<'info, Token>,
}

#[derive(Accounts)]
pub struct WithdrawPoolOracleFeeSol<'info> {
    pub authority: Signer<'info>,
    pub protocol_governance: AccountInfo<'info>,
    pub liquidity_pool: AccountInfo<'info>,
    pub oracle_profile: AccountInfo<'info>,
    #[account(mut)]
    pub pool_oracle_fee_vault: AccountInfo<'info>,
    #[account(mut)]
    pub recipient: AccountInfo<'info>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct CreateAllocationPosition<'info> {
    #[account(mut)]
    pub authority: Signer<'info>,
    pub protocol_governance: AccountInfo<'info>,
    pub liquidity_pool: AccountInfo<'info>,
    pub capital_class: AccountInfo<'info>,
    pub health_plan: AccountInfo<'info>,
    pub funding_line: AccountInfo<'info>,
    #[account(mut)]
    pub allocation_position: AccountInfo<'info>,
    #[account(mut)]
    pub allocation_ledger: AccountInfo<'info>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct UpdateAllocationCaps<'info> {
    pub authority: Signer<'info>,
    pub protocol_governance: AccountInfo<'info>,
    pub liquidity_pool: AccountInfo<'info>,
    #[account(mut, has_one = authority)]
    pub allocation_position: Account<'info, OmegaxProtocolAccount>,
}

#[derive(Accounts)]
pub struct AllocateCapital<'info> {
    pub authority: Signer<'info>,
    pub protocol_governance: AccountInfo<'info>,
    #[account(mut)]
    pub liquidity_pool: AccountInfo<'info>,
    #[account(mut)]
    pub capital_class: AccountInfo<'info>,
    #[account(mut)]
    pub pool_class_ledger: AccountInfo<'info>,
    pub funding_line: AccountInfo<'info>,
    #[account(mut)]
    pub allocation_position: AccountInfo<'info>,
    #[account(mut)]
    pub allocation_ledger: AccountInfo<'info>,
}

#[derive(Accounts)]
pub struct DeallocateCapital<'info> {
    pub authority: Signer<'info>,
    pub protocol_governance: AccountInfo<'info>,
    #[account(mut)]
    pub liquidity_pool: AccountInfo<'info>,
    #[account(mut)]
    pub capital_class: AccountInfo<'info>,
    #[account(mut)]
    pub pool_class_ledger: AccountInfo<'info>,
    pub funding_line: AccountInfo<'info>,
    #[account(mut)]
    pub allocation_position: AccountInfo<'info>,
    #[account(mut)]
    pub allocation_ledger: AccountInfo<'info>,
}

#[derive(Accounts)]
pub struct MarkImpairment<'info> {
    pub authority: Signer<'info>,
    pub protocol_governance: AccountInfo<'info>,
    pub health_plan: AccountInfo<'info>,
    #[account(mut)]
    pub domain_asset_ledger: AccountInfo<'info>,
    #[account(mut)]
    pub funding_line: AccountInfo<'info>,
    #[account(mut)]
    pub funding_line_ledger: AccountInfo<'info>,
    #[account(mut)]
    pub plan_reserve_ledger: AccountInfo<'info>,
    #[account(mut)]
    pub series_reserve_ledger: AccountInfo<'info>,
    #[account(mut)]
    pub pool_class_ledger: AccountInfo<'info>,
    #[account(mut)]
    pub allocation_position: AccountInfo<'info>,
    #[account(mut)]
    pub allocation_ledger: AccountInfo<'info>,
    #[account(mut)]
    pub obligation: AccountInfo<'info>,
}

#[derive(Accounts)]
pub struct RegisterOracle<'info> {
    #[account(mut)]
    pub admin: Signer<'info>,
    #[account(mut, has_one = admin)]
    pub oracle_profile: Account<'info, OmegaxProtocolAccount>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct ClaimOracle<'info> {
    pub oracle: Signer<'info>,
    #[account(mut, has_one = oracle)]
    pub oracle_profile: Account<'info, OmegaxProtocolAccount>,
}

#[derive(Accounts)]
pub struct UpdateOracleProfile<'info> {
    pub authority: Signer<'info>,
    pub protocol_governance: AccountInfo<'info>,
    #[account(mut, has_one = authority)]
    pub oracle_profile: Account<'info, OmegaxProtocolAccount>,
}

#[derive(Accounts)]
pub struct SetPoolOracle<'info> {
    #[account(mut)]
    pub authority: Signer<'info>,
    pub protocol_governance: AccountInfo<'info>,
    pub liquidity_pool: AccountInfo<'info>,
    pub oracle_profile: AccountInfo<'info>,
    #[account(mut, has_one = authority)]
    pub pool_oracle_approval: Account<'info, OmegaxProtocolAccount>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct SetPoolOraclePermissions<'info> {
    #[account(mut)]
    pub authority: Signer<'info>,
    pub protocol_governance: AccountInfo<'info>,
    pub liquidity_pool: AccountInfo<'info>,
    pub oracle_profile: AccountInfo<'info>,
    pub pool_oracle_approval: AccountInfo<'info>,
    #[account(mut, has_one = authority)]
    pub pool_oracle_permission_set: Account<'info, OmegaxProtocolAccount>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct SetPoolOraclePolicy<'info> {
    #[account(mut)]
    pub authority: Signer<'info>,
    pub protocol_governance: AccountInfo<'info>,
    pub liquidity_pool: AccountInfo<'info>,
    #[account(mut, has_one = authority)]
    pub pool_oracle_policy: Account<'info, OmegaxProtocolAccount>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct RegisterOutcomeSchema<'info> {
    #[account(mut)]
    pub publisher: Signer<'info>,
    #[account(mut)]
    pub outcome_schema: AccountInfo<'info>,
    #[account(mut)]
    pub schema_dependency_ledger: AccountInfo<'info>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct VerifyOutcomeSchema<'info> {
    pub governance_authority: Signer<'info>,
    pub protocol_governance: AccountInfo<'info>,
    #[account(mut, has_one = governance_authority)]
    pub outcome_schema: Account<'info, OmegaxProtocolAccount>,
}

#[derive(Accounts)]
pub struct BackfillSchemaDependencyLedger<'info> {
    #[account(mut)]
    pub governance_authority: Signer<'info>,
    pub protocol_governance: AccountInfo<'info>,
    pub outcome_schema: AccountInfo<'info>,
    #[account(mut, has_one = governance_authority)]
    pub schema_dependency_ledger: Account<'info, OmegaxProtocolAccount>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct CloseOutcomeSchema<'info> {
    pub governance_authority: Signer<'info>,
    pub protocol_governance: AccountInfo<'info>,
    #[account(mut)]
    pub outcome_schema: AccountInfo<'info>,
    #[account(mut)]
    pub schema_dependency_ledger: AccountInfo<'info>,
    #[account(mut)]
    pub recipient_system_account: AccountInfo<'info>,
}

#[derive(Accounts)]
pub struct AttestClaimCase<'info> {
    #[account(mut)]
    pub oracle: Signer<'info>,
    pub protocol_governance: AccountInfo<'info>,
    pub health_plan: AccountInfo<'info>,
    pub oracle_profile: AccountInfo<'info>,
    #[account(mut)]
    pub claim_case: AccountInfo<'info>,
    pub funding_line: AccountInfo<'info>,
    pub outcome_schema: AccountInfo<'info>,
    pub liquidity_pool: AccountInfo<'info>,
    pub capital_class: AccountInfo<'info>,
    pub allocation_position: AccountInfo<'info>,
    pub pool_oracle_approval: AccountInfo<'info>,
    pub pool_oracle_permission_set: AccountInfo<'info>,
    pub pool_oracle_policy: AccountInfo<'info>,
    #[account(mut)]
    pub claim_attestation: AccountInfo<'info>,
    pub system_program: Program<'info, System>,
}
// ---- END GENERATED ----
