// ---- GENERATED BY QEDGEN VIA scripts/run_qedgen.mjs ----
#![cfg(kani)]

use omegaxprotocol::state::{
    InitializeProtocolGovernanceArgs,
    SettleClaimCaseArgs,
    SettleClaimCaseSelectedAssetArgs,
    WithdrawArgs,
};

const MAX_CONFIGURED_FEE_BPS: u16 = 9999;
const MAX_SELECTED_ASSET_PAYOUT_OVERPAY_BPS: u16 = 50;

#[kani::proof]
fn protocol_fee_guard_accepts_configured_domain() {
    let protocol_fee_bps: u16 = kani::any();
    let emergency_pause: bool = kani::any();
    kani::assume(protocol_fee_bps <= MAX_CONFIGURED_FEE_BPS);
    let args = InitializeProtocolGovernanceArgs { protocol_fee_bps, emergency_pause };
    assert!(args.protocol_fee_bps <= MAX_CONFIGURED_FEE_BPS);
}

#[kani::proof]
fn claim_payment_guard_keeps_paid_within_approval() {
    let paid_amount: u64 = kani::any();
    let amount: u64 = kani::any();
    kani::assume(amount > 0);
    kani::assume(paid_amount <= u64::MAX - amount);
    let args = SettleClaimCaseArgs { amount };
    let approved_amount = paid_amount + args.amount;
    let next_paid = paid_amount + args.amount;
    assert!(next_paid <= approved_amount);
}

#[kani::proof]
fn selected_asset_guard_bounds_overpay_and_claim_credit() {
    let paid_amount: u64 = kani::any();
    let claim_credit_amount: u64 = kani::any();
    let payout_amount: u64 = kani::any();
    let max_overpay_bps: u16 = kani::any();
    kani::assume(claim_credit_amount > 0);
    kani::assume(payout_amount > 0);
    kani::assume(max_overpay_bps <= MAX_SELECTED_ASSET_PAYOUT_OVERPAY_BPS);
    kani::assume(paid_amount <= u64::MAX - claim_credit_amount);
    let args = SettleClaimCaseSelectedAssetArgs {
        claim_credit_amount,
        payout_amount,
        max_overpay_bps,
    };
    let approved_amount = paid_amount + args.claim_credit_amount;
    let next_paid = paid_amount + args.claim_credit_amount;
    assert!(args.payout_amount > 0);
    assert!(args.max_overpay_bps <= MAX_SELECTED_ASSET_PAYOUT_OVERPAY_BPS);
    assert!(next_paid <= approved_amount);
}

#[kani::proof]
fn fee_withdrawal_guard_stays_within_accrued_fees() {
    let withdrawn_fees: u64 = kani::any();
    let amount: u64 = kani::any();
    kani::assume(amount > 0);
    kani::assume(withdrawn_fees <= u64::MAX - amount);
    let args = WithdrawArgs { amount };
    let accrued_fees = withdrawn_fees + args.amount;
    let next_withdrawn = withdrawn_fees + args.amount;
    assert!(next_withdrawn <= accrued_fees);
}
