// ---- GENERATED BY QEDGEN VIA scripts/run_qedgen.mjs ----
#![cfg(kani)]

use omegaxprotocol::state::{
    InitializeProtocolGovernanceArgs,
    SettleClaimCaseArgs,
    WithdrawArgs,
};

const MAX_CONFIGURED_FEE_BPS: u16 = 9999;
const SAFE_RAIL_CONFIDENCE_BPS: u16 = 25;
const SAFE_RAIL_MAX_CONFIDENCE_BPS: u16 = 100;
const SAFE_RAIL_PRICE_USD_1E8: u64 = 100_000_000;
const SAFE_RAIL_STALENESS_SECONDS: u64 = 3_600;
const SAFE_RAIL_PUBLISHED_AT_TS: u64 = 1;

fn safe_settle_claim_args(amount: u64) -> SettleClaimCaseArgs {
    SettleClaimCaseArgs {
        amount,
        rail_active: true,
        rail_payout_enabled: true,
        rail_price_usd_1e8: SAFE_RAIL_PRICE_USD_1E8,
        rail_max_staleness_seconds: SAFE_RAIL_STALENESS_SECONDS,
        rail_max_confidence_bps: SAFE_RAIL_MAX_CONFIDENCE_BPS,
        rail_last_price_confidence_bps: SAFE_RAIL_CONFIDENCE_BPS,
        rail_last_price_published_at_ts: SAFE_RAIL_PUBLISHED_AT_TS,
    }
}

#[kani::proof]
fn protocol_fee_guard_accepts_configured_domain() {
    let protocol_fee_bps: u16 = kani::any();
    let emergency_pause: bool = kani::any();
    kani::assume(protocol_fee_bps <= MAX_CONFIGURED_FEE_BPS);
    let args = InitializeProtocolGovernanceArgs { protocol_fee_bps, emergency_pause };
    assert!(args.protocol_fee_bps <= MAX_CONFIGURED_FEE_BPS);
}

#[kani::proof]
fn claim_payment_guard_keeps_paid_within_approval() {
    let paid_amount: u64 = kani::any();
    let amount: u64 = kani::any();
    kani::assume(amount > 0);
    kani::assume(paid_amount <= u64::MAX - amount);
    let args = safe_settle_claim_args(amount);
    let approved_amount = paid_amount + args.amount;
    let next_paid = paid_amount + args.amount;
    assert!(next_paid <= approved_amount);
}

#[kani::proof]
fn fee_withdrawal_guard_stays_within_accrued_fees() {
    let withdrawn_fees: u64 = kani::any();
    let amount: u64 = kani::any();
    kani::assume(amount > 0);
    kani::assume(withdrawn_fees <= u64::MAX - amount);
    let args = WithdrawArgs { amount };
    let accrued_fees = withdrawn_fees + args.amount;
    let next_withdrawn = withdrawn_fees + args.amount;
    assert!(next_withdrawn <= accrued_fees);
}
